const PHOTOS_COUNT = 25;
const MIN_LIKES_COUNT = 15;
const MAX_LIKES_COUNT = 200;
const MAX_COMMENTS_COUNT = 15;
const AVATAR_COUNT = 6;
const COMMENTS_PORTION = 5;
const FILE_TYPES = ['gif', 'jpg', 'jpeg', 'png'];
const DEFAULT_PHOTO_URL = 'img/upload-default-image.jpg';
const SCALE_MIN = 25;
const SCALE_MAX = 100;
const SCALE_STEP = 25;

export {
  PHOTOS_COUNT,
  MIN_LIKES_COUNT,
  MAX_LIKES_COUNT,
  MAX_COMMENTS_COUNT,
  AVATAR_COUNT,
  COMMENTS_PORTION,
  FILE_TYPES,
  DEFAULT_PHOTO_URL,
  SCALE_MIN,
  SCALE_MAX,
  SCALE_STEP
};
